[unit_specials]

[unit_specials.Phoenix]
references = []

[unit_specials.Immunity]
references = ["special.immunity"]

[unit_specials.Extra_Damage]
# references are guaranteed, potentials are not
references = []
potential_references = [
    "token.minor_acid",
    "token.poison",
    "token.fire",
    "token.confused",
    "token.insane",
    "token.hypnotized"
]
