[tokens]

[tokens.minor_acid]

name = "Minor Acid"

phase = "Agony 1"

effect = "Role a die, at 3+, unit gets +1 on future damage. At -2, remove minor acid"

[tokens.poison]

name = "Poison"

variable = ["N" = "roll dN"]

phase = "Agony 3"

effect = "Roll a d{N}.
- Ignore armor and regular damage resistances 
- Reduce damage by poison resistances of target
- Apply bonus to damage based on the number +future damage tokens
- Apply damage to the regular damage table.
- If poison killed a model, remove poison.

If poison did not kill a model, downgrade poison one step"


[tokens.confused]

name = "Confused"

phase = "Both gunnery phases and all movement phases"

remove = "Remove one token each pre-assault step in each movement phase"

effect = "Only effects biological units or units with biological crew. While confused, any movement order is replaced by a random move. Roll a d6, on 1-2, rotate unit left, on 3-4 rotate unit right, on 5-6: -."
