[tokens]

[tokens.minor_acid]
name = "Minor Acid"
phases = ["Agony 1"]
remove = "Only as part of effect"
effect = "Role a die, at 3+, unit gets +1 on future damage. Otherwise, remove minor acid"


[tokens.acid]
name = "Acid"
phases = ["Agony 0"]
effect = """Roll a d8 on the following damage table:, 

			 1 : Downgrade from acid to minor acid.
			 2 : +1 to future damage
			 3 : As 2, and if unit has armor, it is reduced by 1 (all directions)
			 4 : As 3, and place a poison cload [4] at hex.
			   : and all units in this hex gets a minor acid token. 
			 5 : As 4, and in addition all units within range=2 gets a minor acid token
			 6 : As 5, and unit gains a terror token.
			 7 : As 6 and unit is set on fire.
			 8 : Roll three times on this table., 
"""

[tokens.terror]
name = "Terror"
phases = ["Agony 0"]
effect = "Acts as if unit has Terror[range=2][6] but effects only units of the same team"

[tokens.poison]
name = "Poison"
short = "[N]"
phases = ["Agony 3"]
effect = """Roll a d{N}.
- Ignore armor and regular damage resistances 
- Reduce damage by poison resistances of target
- Apply bonus to damage based on the number +future damage tokens
- Apply damage to the regular damage table.
- If poison killed a model, remove poison.

If poison did not kill a model, downgrade poison one step"""

[tokens.poison.variables]
N = { type = "int", values = [2, 4, 6, 8, 10, 12] }

[tokens.bleed]
name = "Bleed"
short = "[N]"
phases = ["Agony 4"]
effect = """Roll a d{N}.
At 1, remove bleed token. 

Otherwise
- Ignore armor and regular damage resistances 
- Apply bonus to damage based on the number +future damage tokens
- Apply damage to the regular damage table, with the exception that bleed does not cause more bleed.
- If bleed killed a model, remove bleed.
"""

[tokens.bleed.variables]
N = { type = "int", values = [2, 4, 6, 8, 10, 12] }

[tokens.confused]
name = "Confused"
phases = ["Gunnery 1", "Movement 1", "Movement 2", "Movement 3", "Gunnery 2"]
remove = "Remove one token each pre-assault step in each movement phase"
effect = "Only effects biological units or units with biological crew. While confused, any movement order is replaced by a random move. Roll a d6, on 1-2, rotate unit left, on 3-4 rotate unit right, on 5-6: -."

[tokens.insanity]
name = "Insanity"
phases = ["Movement 1", "Movement 2", "Movement 3"]
remove = "When unit is not longer shaken"
effect = "Can only be given to bio units which are already shaken. Any flee order is treatet at chase, but targets friends or foe alike. If there are two or more equaly valid hexes to move to with chase, the owner still decides where to go"

[tokens.hidden]
name = "Hidden"
phases = []
remove = "You stay hidden until you reveal yourself, in aftermath phase if an enemy is within point blank range, or an enemy special action reveals your location. Cloacking devices stay hidden even if in clear terrain, while all others sources of hidden abilities are revealed if they are in slow or fast in clear terrain within line of sight to an enemy. You only get reveal bonuses if you willingly reveal your self, not if you are forced to."
effect = """While hidden you cannot be fired upon or be assaulted, nor can you fire or assault. You are also immune to Fear and Terror,

While hidden replace the unit with a hidden token. If you have multiple hidden units you do not have to reveal which one is under which token (but you have to keep track your self). In the start of the game you do not have to show the enemy exactly what units you have hidden. (but you have to state how many victory points worth of units that are hidden),

Reveal order: Place your unit within 2 hexes of the hidden token and gain reveal bonuses. In addition to revealing your self as a movement order, you may reveal your self any time you share an hex with an enemy. If so, make an assault and gain the stated reveal bonuses

If you reveal your self you get reveal bonuses: +2 to hit of ranged weapons and pluss 50 percent assault strength and deflection for the first assault you participate in this round."""
