title = "Steampunkfantasy Tournament 2024"

[[armies]]
army = "morten"
label = "Gnome"

[[armies]]
army = "ole_petter"
label = "Dwarf"

[[armies]]
army = "knut"
label = "Ork"

[[armies]]
army = "geir_arne"
label = "Elf"
