[races]

[races.abomination]
name = "Abomination"

[units]
[units.abomination_infantry]
race = "abomination"
name = "Abomination Infantry"
models = [
	"abomination_infantry",
	"abomination_infantry",
	"abomination_infantry",
	"abomination_infantry",
]
size = "Medium"
cost.mp = 8
[units.abomination_infantry.shaken]
speed = "slow"
movement_order = ["-", "-", "flee"]

[units.abomination_infantry.special]
"Take Cover" = "[still][-2]"
"Terror" = "[Range=1][d6]"
"Tentacle" = "If given additional tentacle weapons, they fire simultainiusly with other weapons on regular Fire(s) order, not Fire(b) order"

[units.abomination_infantry.orders.fire]
still = [["Fire(b)", "Fire"], ["Fire", "Fire(b)"], ["-", "Load(2)"], ["-", "Aim"]]
[units.abomination_infantry.orders.movement]
slow = [["360°", "F", "360°"], ["360°", "F", "B"]]
still = [["360°", "360°", "360°"], ["360°", "A ", "F"]]

[units.abomination_infantry.damage_tables]
regular = [
	"1-6: Kill 1 model",
	"7-8: Kill 1 model, psychic damage[d6]",
	"9+: Unit destroyed",
	"{{\\it Note: If one model is killed remove half of the +1 future damage tokens \\\\ and if killed by bleeding/poison, remove that bleeding/poison token}}",
]

psychic = ["4+: shaken"]

[units.horror]
race = "abomination"
name = "Horror"
models = ["horror"]
size = "Huge"
cost.xp = 8
armor = [6, 4, 2, 1]
[units.horror.shaken]
speed = "still"
movement_order = ["-", "-", "-"]

[units.horror.special]
"Terror" = "While in fog (in agony phases): Terror[Range=1][d12], Insanity Filed[range=1][d6]"
"Fog" = "If horror is either standing in a hex with fog or entering a hex with fog, threat the hex as impassable for enemy chase purposes, forcing them to move into another squar without assault taking place."
"Poison Cloud" = "Treat any squares within range 2 of Horror as being a poison cloud[4]"
"Immunity" = "acid and fire, poison resistance 12"
"Forward Position" = "[3]"

[units.horror.orders.movement]
slow = [["360°", "F", "360°"], ["360°", "F", "B"]]
still = [["360°", "360°", "360°"], ["360°", "A ", "F"]]

[units.horror.damage_tables]
regular = [
	"1-3: Bleed[6]",
	"4-5: As below, +1 to future damage",
	"6-8: As below, if caused by bleeding, amplify bleeding",
	"9+: Unit destroyed",
	"{{\\it Note:  Amplify bleeding: Bleed[4] becomes Bleed[6], Bleed[6] becomes Bleed[8] etc up to max Bleed[12]}}",
	"{{\\it Note: bleeding does not cause more bleeding}}",
]

psychic = ["6+: shaken"]


[units.robot_crab]
race = "abomination"
name = "Robot Crab"
models = [
	"robot_crab",
	"robot_crab",
	"robot_crab",
	"robot_crab",
	"robot_crab",
	"robot_crab",
]
size = "Tiny"
cost.cp = 1
armor = [3, 3, 3, 3]
[units.robot_crab.shaken]
speed = "still"
movement_order = ["-", "-", "-"]

[units.robot_crab.special]
"Chase" = "Primary target for all chase orders are enemies drone. Move towards nearest enemy robot instead of nearest enemy. If there are no enemy robots, treat it as normal chase instead"

[units.robot_crab.orders.movement]
fast = [["chase", "chase", "chase"]]

[units.robot_crab.damage_tables]
regular = ["1-8: Kill 1 model", "9+: Unit destroyed"]


[units.giant_frog_riders]
race = "abomination"
name = "Giant Frog Riders"
models = ["giant_frog_rider", "giant_frog_rider"]
size = "Medium"
cost.mp = 2
cost.xp = 4
[units.giant_frog_riders.shaken]
speed = "slow"
movement_order = ["-", "-", "flee"]

[units.giant_frog_riders.special]
"Resistance" = "Poison [4]"
"Terror" = "[range=1][d8]"



[units.giant_frog_riders.orders.fire]
still = [["-", "Load"], ["Load", "-"]]
slow = [["-", "Load"], ["Load", "-"]]
fast = [["-", "Load"], ["Load", "-"]]

[units.giant_frog_riders.orders.movement]
fast = [["360°", "F", "F"], ["F", "F", "360°"], ["F", "360°", "F"], ["F", "B", "-"]]
slow = [["360°", "A", "F"], ["B", "360°", "-"], ["360°", "F", "360°"]]
still = [["360°", "A", "F"], ["360°", "360°", "360°"]]


[units.giant_frog_riders.damage_tables]
regular = [
	"2-3: bleed[4]",
	"4+: kill 1 model",
	"{{\\it Note: If one model is killed remove half of the +1 future damage tokens \\\\ and if killed by bleeding/poison, remove that bleeding/poison token}}",
]
psychic = ["6+: shaken"]


[units.hippopotamus_riders]
race = "abomination"
name = "Hippopotamus Riders"
models = ["hippopotamus_riders"]
size = "Large"
cost.mp = 2
cost.xp = 8
armor = [6, 5, 4, 2]
[units.hippopotamus_riders.shaken]
speed = "fast"
movement_order = ["-", "chase", "chase"]
fire_order = "Normal"

[units.hippopotamus_riders.special]
"Resistance" = "Poison [6]"
"Fire Order" = "Fire(mm) fires multipuropose mortar, while Fire(om) fire oversized muskets.  Both weapons must be fired if loaded, and each weapon uses 1 ammo."


[units.hippopotamus_riders.orders.fire]
still = [["Load", "Load"], ["Fire(mm)", "Fire(om)"], ["Fire(om)", "Fire(mm)"]]
slow = [["Load", "Load"], ["Fire(mm)", "Fire(om)"], ["Fire(om)", "Fire(mm)"]]
fast = [["Load", "Load"], ["Fire(mm)", "Fire(om)"], ["Fire(om)", "Fire(mm)"]]

[units.hippopotamus_riders.orders.movement]
fast = [
	[
		"360°",
		"F",
		"F",
	],
	[
		"F",
		"F",
		"360°",
	],
	[
		"F",
		"360°",
		"F",
	],
	[
		"F",
		"B",
		"-",
	],
	[
		"-",
		"Chase",
		"Chase",
	],
]
slow = [["360°", "A", "F"], ["B", "360°", "-"], ["360°", "F", "360°"]]
still = [["360°", "A", "F"], ["360°", "360°", "360°"]]


[units.hippopotamus_riders.damage_tables]
regular = [
	"2-3: bleed[4]",
	"4-6: as below, +1 to future damage",
	"7-8: as below, Shaken",
	"9+: unit destroyed",
	"{{\\it Note: bleeding does not cause more bleeding}}",
]
psychic = ["6+: shaken"]


[units.squ]
race = "abomination"
name = "Squ"
models = ["squ"]
size = "Large"
armor = [8, 6, 5, 4]
cost.ip = 6
[units.squ.shaken]
speed = "still"
movement_order = ["-", "-", "-"]



[units.squ.orders.movement]
slow = [
	[
		"L/R",
		"-",
		"-",
	],
	[
		"L/R",
		"L/R",
		"-",
	],
	[
		"F",
		"L/R",
		"-",
	],
	[
		"B",
		"-",
		"-",
	],
	[
		"A",
		"-",
		"-",
	],
	[
		"F",
		"-",
		"-",
	],
	[
		"B",
		"rev",
		"-",
	],
]

still = [
	[
		"L/R",
		"-",
		"-",
	],
	[
		"L/R",
		"L/R",
		"-",
	],
	[
		"L/R",
		"L/R",
		"L/R",
	],
	[
		"-",
		"-",
		"-",
	],
	[
		"L/R",
		"A",
		"F",
	],
	[
		"A",
		"F",
		"-",
	],
	[
		"rev",
		"-",
		"-",
	],
]
fast = [["F", "F", "-"], ["F", "B", "-"]]

[units.squ.orders.fire]
slow = [["-", "Load"], ["-", "Fire"]]
fast = [["-", "Load"], ["-", "Fire"]]
still = [["-", "Load"], ["-", "Fire"], ["-", "Aim"]]

[units.squ.damage_tables]
regular = [
	"1-3: +1 to future damage",
	"4: as below, shaken",
	"5-8: as below, d6 critical damage",
	"9: Unit destroyed",
]
critical = [
	"1-2: +3 to future damage",
	"3: +1 to be hit, -1 to hit",
	"4: Cannot rotate",
	"5: Unit cannot Move ",
	"6: set on fire",
]
crew = [
	"4-5: Crippled Crew, if already shaken double initial crew damage",
	"6-7: as 4-5, shaken",
	"8-11: as 6-7, +3 to future crew damage",
	"12: Unit destroyed",
]


[units.frost88]
race = "abomination"
name = "Frost 88"
models = ["frost88"]
size = "Large"
armor = [10, 8, 7, 6]
cost.ip = 12
[units.frost88.shaken]
speed = "still"
movement_order = ["-", "-", "-"]

[units.frost88.special]
"Fire Order" = "Fire(g) fires the main gun, while Fire(fr) fires frost ray. Track ammo only for main gun"


[units.frost88.orders.movement]
slow = [
	[
		"L/R",
		"-",
		"-",
	],
	[
		"L/R",
		"L/R",
		"-",
	],
	[
		"F",
		"L/R",
		"-",
	],
	[
		"B",
		"-",
		"-",
	],
	[
		"A",
		"-",
		"-",
	],
	[
		"F",
		"-",
		"-",
	],
	[
		"B",
		"rev",
		"-",
	],
]

still = [
	[
		"L/R",
		"-",
		"-",
	],
	[
		"L/R",
		"L/R",
		"-",
	],
	[
		"L/R",
		"L/R",
		"L/R",
	],
	[
		"-",
		"-",
		"-",
	],
	[
		"L/R",
		"A",
		"F",
	],
	[
		"A",
		"F",
		"-",
	],
	[
		"rev",
		"-",
		"-",
	],
]
fast = [["F", "F", "-"], ["F", "B", "-"]]

[units.frost88.orders.fire]
slow = [["Load", "Fire(fr)"], ["Fire(g)", "Fire(fr)"]]
fast = [["Load", "Fire(fr)"], ["Fire(g)", "Fire(fr)"]]
still = [
	[
		"Load",
		"Fire(fr)",
	],
	[
		"Fire(g)",
		"Fire(fr)",
	],
	[
		"-",
		"Aim",
	],
	[
		"Aim",
		"Fire(fr)",
	],
]

[units.frost88.damage_tables]
regular = [
	"1-3: +1 to future damage",
	"4: as below, shaken",
	"5-8: as below, d6 critical damage",
	"9: Unit destroyed",
]
critical = [
	"1: +3 to future damage",
	"2: +1 to be hit, -1 to hit",
	"3: Cannot rotate",
	"4-5: Unit cannot Move ",
	"6: set on fire",
]
crew = [
	"4-5: Crippled Crew, if already shaken double initial crew damage",
	"6-7: as 4-5, shaken",
	"8-11: as 6-7, +3 to future crew damage",
	"12: Unit destroyed",
]


[models]
[models.abomination_infantry]
name = "Abomination Infantry"
race = "abomination"
equipment_limit = ["Independent:∞", "Hands:2", "Tentacles:4"]
equipments = ["multipurpose_gun"]
type = ["Bio", "Infantry", "Walking", "Amphibian"]

[models.abomination_infantry.special]
"Fog" = "Double to-hit penalties in smoke/fog and ignore to-hit penalty for enemies in smoke/fog. (however does not ignore line of sight through smoke/fog) hexes. "



[models.abomination_infantry.assault]
strength = [1, 1, 1, 1]
strength_die = "6+"
deflection = [1, 0, 0, 0]
deflection_die = "6+"
damage = "d6-2"
ap = 2

[models.abomination_infantry.assault.special]
"Bonus" = "+100\\% strength and deflections versus shaken units"
"Cunning Assault" = "[1 for 2]"


[models.hippopotamus_riders]
name = "Hippopotamus Riders"
race = "abomination"
equipment_limit = ["Independent:∞"]
equipments = ["multipurpose_mortar", "oversized_musket"]
type = ["Bio", "Walking", "Amphibian"]

[models.hippopotamus_riders.special]
"To Hit" = "Double to-hit bonuses and penalties for movement speed, both for you and the target"

[models.hippopotamus_riders.assault]
strength = [12, 6, 3, 3]
strength_die = "6+"
deflection = [2, 0, 0, 0]
deflection_die = "6+"
damage = "d6"
ap = 2


[models.hippopotamus_riders.assault.special]
"Bonus" = "+100\\% strength and deflections versus shaken units"




[models.horror]
name = "Horror"
race = "abomination"
equipment_limit = ["Independent:∞"]
equipments = []
type = ["Bio", "Monster", "Walking", "Amphibian"]

[models.horror.assault]
strength = [6, 4, 4, 2]
strength_die = "4+"
deflection = [2, 0, 0, 0]
deflection_die = "4+"
damage = "d6"
ap = 2

[models.horror.assault.special]
"Bonus" = "+100\\% strength and deflections versus shaken units"

[models.robot_crab]
name = "Robot Crab"
race = "abomination"
equipment_limit = []
equipments = []
type = ["Drone", "Walking"]

[models.robot_crab.assault]
strength = [1, 1, 1, 1]
strength_die = "6+"
deflection = [1, 0, 0, 0]
deflection_die = "6+"
damage = "d6"
ap = 0



[models.robot_crab.assault.special]
"Bonus" = "+100\\% strength and deflections versus shaken units"
"Cunning Assault" = "[1 for 1]"


[models.squ]
name = "Squ"
race = "abomination"
equipments = ["confution_gas_launcher"]
equipment_limit = ["Independent:∞", "Mechanical Tentacles:2"]
type = ["Vehicle", "Mechanical", "Tracked", "Bio Crew"]

[models.squ.special]
"Fog" = "Double to-hit penalties in fog and ignore to-hit penalty for enemies in fog. (however does not ignore line of sight through fog hexes)"

[models.squ.assault]
strength = [12, 1, 1, 1]
strength_die = "6+"
deflection = [6, 0, 0, 0]
deflection_die = "6+"
damage = "d6-2"
ap = 2

[models.squ.assault.special]
"Bonus" = "+100\\% strength and deflections versus shaken units"



[models.frost88]
name = "Frost88"
race = "abomination"
equipments = ["twin_frost_ray", "main_gun"]
equipment_limit = ["Independent:∞"]
type = ["Vehicle", "Mechanical", "Tracked", "Bio Crew"]

[models.frost88.special]
"Fog" = "Double to-hit penalties in smoke/fog and ignore to-hit penalty for enemies in smoke/fog. (however does not ignore line of sight through smoke/fog hexes)"
"To Hit" = "Double to hit bonuses and penalties for movement, both your own and the enemies"


[models.frost88.assault]
strength = [10, 1, 1, 1]
strength_die = "6+"
deflection = [8, 2, 0, 0]
deflection_die = "6+"
damage = "d6-2"
ap = 2

[models.frost88.assault.special]
"Bonus" = "+100\\% strength and deflections versus shaken units"


[models.elite_abomination_infantry]
name = "Elite Abomination Infantry"
race = "abomination"
cost.xp = 1
equipment_limit = ["Independent:∞", "Hands:2", "Tentacles:8"]
equipments = ["multipurpose_gun"]
type = ["Bio", "Infantry", "Elite", "Walking"]
replaces = "abomination_infantry"

[models.elite_abomination_infantry.special]
"To Hit" = "good shot: +1 to hit"
"Vulnerability" ="All enemies within range 2 gets psycic vulnerability of 1: Increase psycic damage they take by 1. This ability does not stack"

[models.elite_abomination_infantry.assault]
strength = [2, 1, 1, 1]
strength_die = "6+"
deflection = [2, 0, 0, 0]
deflection_die = "6+"
damage = "d6-2"
ap = 2

[models.elite_abomination_infantry.assault.special]
"Bonus" = "+100\\% strength and deflections versus shaken units"
"Cunning Assault" = "[1 for 2]"


[models.giant_frog_rider]
name = "Giant Frog Rider"
race = "abomination"
equipment_limit = ["Independent:∞", "Hands:2", "Tentacles:4"]
equipments = ["frog_spit", "mechanical_melee_contraption"]
type = ["Bio", "Cavalry", "Walking", "Amphibian", "Frog"]


[models.giant_frog_rider.special]
"Fog" = "Double to-hit penalties in fog and ignore to-hit penalty for enemies in fog. (however does not ignore line of sight through fog hexes)"

[models.giant_frog_rider.assault]
strength = [4, 1, 1, 1]
strength_die = "6+"
deflection = [4, 0, 0, 0]
deflection_die = "6+"
damage = "d6"
ap = 2

[models.giant_frog_rider.assault.special]
	"Damage" = "Poison[4]"
	"Cunning Assault" = "[1 for 3]"
	"Bonus" = "+100\\% strength and deflections versus shaken units"


[equipments]

[equipments.confution_gas_launcher]
name = "Confution Gas launcher"
race = "abomination"

[equipments.confution_gas_launcher.range]
range = 4
angle = [true, true, false, false]
damage = "d6 psychic + d4 crew damage"
ap = "N/A"
special = [
	"Fires 3 shot per fire order. Each hit gives one confution token to any unit with bio or a bio crew. (se general rules)",
]


[equipments.multipurpose_gun]
name = "Multipurpose Gun"
race = "abomination"
requires = [["Hands:2"]]

[equipments.multipurpose_gun.range]
range = 5
angle = [true, true, true, true]
damage = "d6 psychic"
ap = "N/A"
special = [
	"Has two settings. Scare and blow gun. Scare do the regular psychic damage, used by Fire orders. Blow gun is used by Fire(b) orders and only effect shaken bio units. All other units are immune. However, if you manage to cause psycic damage the unit becomes insane in addition to the normal effects of the psycic damage table",
]

[equipments.tentacle_craclespears]
name = "Tentacle CracleSpears"
race = "abomination"
cost.cp = 2
requires = [["Tentacles:2"], ["type:Infantry", "type:Cavalry"]]
#requires = [["type:Infantry","type:Cavalry"]]

[equipments.tentacle_craclespears.assault]

strength.add = [1, 0, 0, 0]
deflection.add = [1, 0, 0, 0]
deflection_die.replace = "6+" # TODO: use max and add "max" to data.py, line 1120ish


[equipments.tentacle_craclespears.assault.special]
	"Damage" = "If assault in a hex with fog (smoke token), each hit by this model does an d6 psycic damage in addition to the regular damage. This ability does not stack with more spears."


[equipments.tentacle_axes]
name = "Tentacle Axes"
race = "abomination"
cost.cp = 1
requires = [["Tentacles:2"], ["type:Infantry", "type:Cavalry"]]

[equipments.tentacle_axes.assault]

strength.add = [2, 0, 0, 0]


[equipments.tentacle_shield]
name = "Tentacle Shield"
race = "abomination"
cost.cp = 2
requires = [["Tentacles:1"], ["type:Infantry"]]

[equipments.tentacle_shield.unit_special]

"Protection" = "Unit gain [3, 0, 0, 0] in armor. Do not stack"

[equipments.tentacle_shield.assault]

deflection.add = [2, 0, 0, 0]
deflection_die.replace = "5+"


[equipments.frog_armor]
name = "Frog Cavalry Armor"
race = "abomination"
cost.cp = 2
requires = [["type:Frog"]]

[equipments.frog_armor.unit_special]
"Protection" = "Unit gain [4, 3, 3, 0] in armor."


[equipments.fog_grenade_mortar]
name = "Fog grenade Mortar"
race = "abomination"
cost.cp = 4
requires = [["Tentacles:4"], ["type:Infantry"]]


[equipments.fog_grenade_mortar.range]
range = 4
angle = [true, true, true, true]
damage = "N/A"
ap = "N/A"
special = [
	"Place two smoke tokens in a hex within normal range. Note: choose one hex per model firing this weapon. Uses Ammo as normal. May start the game without ammo, but instead place two smoke tokens in 4 different hexes within range 3 of this unit at start of game (part of setup)",
]


[equipments.multipurpose_mortar]
name = "Multipurpose Mortar"
race = "abomination"


[equipments.multipurpose_mortar.range]
range = 3
angle = [true, true, true, true]
damage = "N/A"
ap = "N/A"
special = [
	"Either Place two fog tokens in two different hexes, or give two different units one minor acid each, or place two poison cloud[4] in two different hexes. All targets must be within normal range.",
]


[equipments.oversized_musket]
name = "Dobble Barrled Oversized Musket"
race = "abomination"


[equipments.oversized_musket.range]
range = 4
angle = [true, false, false, false]
damage = "d8"
ap = "3"
special = ["Fire two shot per fire order", "Gear disruption[6+]"]


[equipments.tentacle_dart]
name = "Tentacle Dart"
race = "abomination"
cost.cp = 1
requires = [["Tentacles:1"], ["type:Infantry", "type:Cavalry"]]


[equipments.tentacle_dart.range]
range = 2
angle = [true, true, true, true]
damage = "d6-2"
ap = 1
special = []


[equipments.frog_spit]
name = "Frog spit"
race = "abomination"
requires = []

[equipments.frog_spit.range]
range = 1
angle = [true, true, false, false]
damage = "N/A"
ap = "N/A"
special = [
	"Poison[4]",
	"Always treated as loaded, and fire in both first and second gunnery phase independent of other weapons",
]


[equipments.twin_frost_ray]
name = "Twin Frost Ray"
race = "abomination"
requires = []

[equipments.twin_frost_ray.range]
range = 4
angle = [true, false, false, false]
damage = "d4-2+d6 psychic damage + d4 crew damage"
ap = 0
special = [
	"Fire twice per fire order",
	"Always treated as loaded",
	"The target must break if possible (if it has a lower speed available). Reduce the speed one step",
]


[equipments.main_gun]
name = "Main Gun"
race = "abomination"
requires = []

[equipments.main_gun.range]
range = 4
angle = [true, false, false, false]
damage = "d6 (+d8 crew damage if penetrating all armor)"
ap = 6
special = ["Gear Disruption[5+]"]


[equipments.mechanical_melee_contraption]
name = "Mechanical Melee Contraption"
race = "abomination"
requires = []


[equipments.mechanical_melee_contraption.assault.special]

	"Improvement" = "Improves assault if ammo is spend. You may spend one ammo in an assault, to increase the success of both assault strength and deflection to 4+ instead of 6+"
